name: convert DOIs json arrax to bib file
on:
  workflow_dispatch:
    
  push:
    paths:
      - assets/dois.json
jobs:
  dois2bib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install parallel jq curl -y
      - run: cat assets/dois.json | jq -r '.[]' | parallel -j8 -k "content_type=\$(curl -s -o /dev/null -I -L -w '%{content_type}\n' -H 'Accept:application/x-bibtex' 'https://doi.org/{}') && [[ \"\$content_type\" == 'application/x-bibtex'* ]] && curl -s -LH 'Accept:application/x-bibtex' 'https://doi.org/{}'; echo" | sed '/^$/d' | sort | awk -F, '{ count[$1]++; if (count[$1] == 1) { print $0; } else { print $1 "_" count[$1] - 1 FS $2; }}' > assets/mg_temp.bib
      - run: awk '/^@.*,$/ {gsub(/,/, "_"count++ ",")} {print}' assets/mg_temp.bib > assets/mg.bib
      - run: sed -i 's/\$\\greater\$/>/g; s/\$\\less\$/</g' assets/mg.bib  
      - run: sed -i 's/\$[^$]*\$//g' assets/mg.bib
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'assets/mg.bib'
          message: update mg.bib
          committer_name: GitHub Actions
          committer_email: github-actions[bot]@users.noreply.github.com
