name: convert DOIs json arrax to bib file
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
  push:
    paths:
      - assets/dois.json
jobs:
  dois2bib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: apt-get install parallel jq curl -y
      - run: |
        cat assets/dois.json| jq -r '.[]' | parallel -j8 "(curl -s -LH 'Accept: application/x-bibtex' 'https://doi.org/{}'; echo )"> assets/mg.bib
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'assets/mg.bib'
          message: update mg.bib
          committer_name: GitHub Actions
          committer_email: github-actions[bot]@users.noreply.github.com
